name: Node.js CI/CD with PM2

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
          scope: "@awesome-nest-generator"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install PM2
        run: pnpm install pm2@latest -g

      - name: Deploy to Development
        run: pm2 deploy '.ecosystem/ecosystem.dev.config.js' develop setup
        # run: pm2 deploy '.ecosystem/ecosystem.dev.config.js' develop

  deploy-production:
    name: Deploy to Production
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
          scope: "@awesome-nest-generator"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install PM2
        run: pnpm install pm2@latest -g

      - name: Deploy to Production
        run: pm2 deploy '.ecosystem/ecosystem.prod.config.js' production setup
        # run: pm2 deploy '.ecosystem/ecosystem.prod.config.js' production
