name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.0

      - name: Setup Node.js and PM2
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Install dependencies
        run: pnpm install

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 18.141.176.61 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: pm2 deploy ./.ecosystem/ecosystem.dev.config.js develop

      - name: Notify deployment success
        if: always()
        run: echo "Deployment to EC2 successful"
